// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", false);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.user_id", "0c35d5b7-8108-43e0-a2e3-9b10b667cb0b");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1543753377);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1543753497);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1543793183);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1543774736);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1543774616);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1543753256);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1543752776);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1543753617);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.lastDir", "/home/alex/Images");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1543660661);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 74);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b1f3f816-e597-4b38-a3d8-680c3abfd102}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1543708800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1543793093);
user_pref("browser.onboarding.notification.prompt-count", 5);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1543794766782");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1543796541782");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1543793902979");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1543797502979");
user_pref("browser.search.cohort", "nov17-1");
user_pref("browser.search.region", "GB");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181116104104");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1543785953");
user_pref("browser.slowStartup.averageTime", 1165);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20181116104104");
user_pref("browser.startup.homepage_override.mstone", "63.0.3");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1543660664418");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "63.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "8a815138b1be44d9b0b496625847c56a");
user_pref("extensions.blocklist.lastModified", "Mon, 26 Nov 2018 14:19:56 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1543753377);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181116104104");
user_pref("extensions.lastAppVersion", "63.0.3");
user_pref("extensions.lastPlatformVersion", "63.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{6dd64a2e-b8d8-407f-8366-029a9be497ee}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4fd50019-3846-40bb-95d2-3615c60ed649\",\"webcompat@mozilla.org\":\"809f5223-c499-445c-b8a0-acf466f9de69\",\"screenshots@mozilla.org\":\"831cc998-2cfe-4d9a-855c-343cb4841ee6\",\"fxmonitor@mozilla.org\":\"236796ac-425a-4f16-bcec-cc89d25b2012\"}");
user_pref("font.internaluseonly.changed", false);
user_pref("idle.lastDailyNotification", 1543752940);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.benchmark.vp9.fps", 264);
user_pref("media.benchmark.vp9.versioncheck", 5);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1543662388);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181116104104");
user_pref("media.gmp-manager.lastCheck", 1543752780);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1543752940);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "0d87477f-e64c-44c5-900b-16cf185df255");
user_pref("services.blocklist.addons.checked", 1543753351);
user_pref("services.blocklist.gfx.checked", 1543753351);
user_pref("services.blocklist.onecrl.checked", 1543753351);
user_pref("services.blocklist.pinning.checked", 1543753351);
user_pref("services.blocklist.plugins.checked", 1543753351);
user_pref("services.settings.clock_skew_seconds", -95);
user_pref("services.settings.last_update_seconds", 1543753351);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1543753351);
user_pref("services.settings.main.tippytop.last_check", 1543753351);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1543752940);
user_pref("toolkit.startup.last_success", 1543785953);
user_pref("toolkit.telemetry.cachedClientID", "3a17369c-8879-429d-affe-dee16d2085f0");
user_pref("toolkit.telemetry.previousBuildID", "20181116104104");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
